// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa4FDKIyVPis4SsbBsCfmzjEQrvBxSn8s',
    appId: '1:535042158426:web:ec47167865abfd3e0fcd63',
    messagingSenderId: '535042158426',
    projectId: 'whtsapclone-29d24',
    authDomain: 'whtsapclone-29d24.firebaseapp.com',
    storageBucket: 'whtsapclone-29d24.appspot.com',
    measurementId: 'G-Q52VJ7HBKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzBU1aXoXlN2RdHY7Rgd3RmpROfM1J0RQ',
    appId: '1:535042158426:android:290d48e277af9c110fcd63',
    messagingSenderId: '535042158426',
    projectId: 'whtsapclone-29d24',
    storageBucket: 'whtsapclone-29d24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgV8b0plRs7GTQ8dtTSshfuF4TQH0QNXw',
    appId: '1:535042158426:ios:e7bcfbc116f737070fcd63',
    messagingSenderId: '535042158426',
    projectId: 'whtsapclone-29d24',
    storageBucket: 'whtsapclone-29d24.appspot.com',
    iosClientId: '535042158426-ara5nl6vsq0no3ag7lksufcbhf16a6nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgV8b0plRs7GTQ8dtTSshfuF4TQH0QNXw',
    appId: '1:535042158426:ios:74b6ebad239ca0c90fcd63',
    messagingSenderId: '535042158426',
    projectId: 'whtsapclone-29d24',
    storageBucket: 'whtsapclone-29d24.appspot.com',
    iosClientId: '535042158426-ie168u1a0s2flrfmgrek6mqe23lhkjd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
